import { useEffect } from 'react'
import { useSelector } from 'react-redux'
import Head from 'next/head'

import { fetchPeople } from '../../redux/asyncActions'
import { peopleSelector } from '../../redux/slices/people'
import PersonCard from '../../components/PersonCard'

import styles from './People.module.scss'
import { useAppDispatch } from '../../redux/store'

const People = () => {
  const dispatch = useAppDispatch()

  const users = useSelector(peopleSelector)

  useEffect(() => {
    dispatch(fetchPeople())
  }, [])
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {users.map((item) => (
        <PersonCard item={item} avatar={item.avatarUrl} />
      ))}
    </div>
  )
}

export default People
