import { useEffect } from 'react'
import { useSelector } from 'react-redux'
import Head from 'next/head'

import { fetchPeople } from '../../redux/asyncActions'
import { peopleSelector } from '../../redux/slices/people'
import PersonCard from '../../components/PersonCard'
import { useAppDispatch } from '../../redux/store'

import styles from './People.module.scss'
import Paper from '@mui/material/Paper'
import { Divider } from '@mui/material'

const People = () => {
  const dispatch = useAppDispatch()

  const users = useSelector(peopleSelector)

  useEffect(() => {
    dispatch(fetchPeople())
  }, [])

  return (
    <Paper className={styles.paper}>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <div className={styles.list}>
          {users.map((item) => (
            <div>
              <div className={styles.item}>
                <PersonCard item={item} avatar={item.avatarUrl} />
              </div>
              <Divider />
            </div>
          ))}
        </div>
      </div>
    </Paper>
  )
}

export default People
