import Head from 'next/head'
import { useEffect } from 'react'
import { useSelector } from 'react-redux'
import ImagesGrid from '../components/ImagesGrid'
import { fetchPosts, fetchTags } from '../redux/asyncActions'
import { postsSelector } from '../redux/slices/posts'
import { useAppDispatch } from '../redux/store'
import styles from '../styles/Home.module.css'

export default function Home() {
  const dispatch = useAppDispatch()
  const { posts, tags } = useSelector(postsSelector)

  const isPostsLoading = posts.status === 'loading'
  const isTagsLoading = tags.status === 'loading'

  useEffect(() => {
    dispatch(fetchPosts())
    dispatch(fetchTags())
  }, [])
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <ImagesGrid />
    </div>
  )
}
